= asn-one - ASN.1 library for Java
Jeroen van Erp
:asn_groupid: com.hierynomus
:asn_version: 0.5.0
:source-highlighter: pygments

image:https://api.bintray.com/packages/hierynomus/maven/asn-ons/images/download.svg[link="https://bintray.com/hierynomus/maven/asn-one/_latestVersion"] image:https://travis-ci.org/hierynomus/asn-one.svg?branch=master["Build Status", link="https://travis-ci.org/hierynomus/asn-one"] image:https://api.codacy.com/project/badge/Grade/f7eb9b6b372b4ce4a0fac2af65acaaed["Codacy code quality", link="https://www.codacy.com/app/jeroen_2/asn-one?utm_source=github.com&utm_medium=referral&utm_content=hierynomus/asn-one&utm_campaign=Badge_Grade"] image:https://javadoc-emblem.rhcloud.com/doc/com.hierynomus/asn-one/badge.svg["Javadoc",link="http://www.javadoc.io/doc/com.hierynomus/asn-one"] image:https://maven-badges.herokuapp.com/maven-central/com.hierynomus/asn-one/badge.svg["Maven Central",link="https://maven-badges.herokuapp.com/maven-central/com.hierynomus/asn-one"]

== What is asn-one
asn-one is a pure Java implementation of an ASN.1 encoder and decoder. It supports the BER and DER encoding rules of the bytestream. It is designed to be as lightweight as possible by having minimized the external dependencies. It only depends on the SLF4J logging API.

== Getting asn-one
To get asn-one, you have two options:

. Add a dependency to asn-one to your project.
. Build asn-one yourself.

Binary releases of asn-one are not provided here, but you can download it http://search.maven.org/#artifactdetails%7C{asn_groupid}%7Csmbj%7C{asn_version}%7Cjar[straight from the Maven Central repository] if you want to.

== Depending on asn-one
If you're building your project using Maven, you can add the following dependency to the `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>{asn_groupid}</groupId>
  <artifactId>asn-one</artifactId>
  <version>{asn_version}</version>
</dependency>
----

If your project is built using another build tool that uses the Maven Central repository, translate this dependency into the format used by your build tool.

== Building asn-one
. Clone the asn-one repository.
. Run the command `./gradlew clean build`.

== Release History
v0.4.0 (2018-10-11)::
- Moved groupID to 'com.hierynomus' to be in line with other libraries
v0.3.0 (2018-10-10)::
- Implemented serialization and deserialization in streams
v0.2.0 (unreleased)::
v0.1.0 (2016-11-25)::
- Initial release, containing most standard types
